/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void txtMsgFromZumo_change1(GTextArea source, GEvent event) { //_CODE_:txtMsgFromZumo:653858:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtMsgFromZumo:653858:

public void btnLeft_click1(GButton source, GEvent event) { //_CODE_:btnLeft:308221:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('A');
  println("A"); 
} //_CODE_:btnLeft:308221:

public void btnRight_click1(GButton source, GEvent event) { //_CODE_:btnRight:604378:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('D');
  println("D"); 
} //_CODE_:btnRight:604378:

public void btnForward_click1(GButton source, GEvent event) { //_CODE_:btnForward:348760:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('W');
  println("W");   
} //_CODE_:btnForward:348760:

public void btnBack_click1(GButton source, GEvent event) { //_CODE_:btnBack:984108:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('S');
  println("S"); 
} //_CODE_:btnBack:984108:

public void btnStop_click1(GButton source, GEvent event) { //_CODE_:btnStop:697225:
  println("btnStop - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('Q');
  println("Q");
} //_CODE_:btnStop:697225:

public void btnSignalRoomL_click1(GButton source, GEvent event) { //_CODE_:btnSignalRoomL:454490:
  println("btnSignalRoomL - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('L');
  println("L");  
} //_CODE_:btnSignalRoomL:454490:

public void btnSignalRoomR_click1(GButton source, GEvent event) { //_CODE_:btnSignalRoomR:425371:
  println("btnSignalRoomR - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('R');
  println("R");
} //_CODE_:btnSignalRoomR:425371:

public void btnSignalCorridorL_click1(GButton source, GEvent event) { //_CODE_:btnSignalCorridorL:233786:
  println("btnSignalCorridor - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('C');
  println("C");
} //_CODE_:btnSignalCorridorL:233786:

public void btnScan_click1(GButton source, GEvent event) { //_CODE_:btnScan:211834:
  println("btnScan - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('X');
  println("X");
} //_CODE_:btnScan:211834:

public void btnSignalCorridorR_click1(GButton source, GEvent event) { //_CODE_:btnSignalCorridorR:730786:
  println("R - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('V');
  println("V");
} //_CODE_:btnSignalCorridorR:730786:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  txtMsgFromZumo = new GTextArea(this, 290, 99, 198, 199, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  txtMsgFromZumo.setText("Messages from Zumo");
  txtMsgFromZumo.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  txtMsgFromZumo.setOpaque(true);
  txtMsgFromZumo.addEventHandler(this, "txtMsgFromZumo_change1");
  btnLeft = new GButton(this, 10, 100, 80, 30);
  btnLeft.setText("Left");
  btnLeft.setTextBold();
  btnLeft.addEventHandler(this, "btnLeft_click1");
  btnRight = new GButton(this, 190, 100, 80, 31);
  btnRight.setText("Right");
  btnRight.setTextBold();
  btnRight.addEventHandler(this, "btnRight_click1");
  btnForward = new GButton(this, 100, 60, 80, 30);
  btnForward.setText("Forward");
  btnForward.setTextBold();
  btnForward.addEventHandler(this, "btnForward_click1");
  btnBack = new GButton(this, 100, 140, 80, 30);
  btnBack.setText("Back");
  btnBack.setTextBold();
  btnBack.addEventHandler(this, "btnBack_click1");
  btnStop = new GButton(this, 100, 100, 80, 29);
  btnStop.setText("Stop");
  btnStop.setTextBold();
  btnStop.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStop.addEventHandler(this, "btnStop_click1");
  btnSignalRoomL = new GButton(this, 50, 230, 80, 30);
  btnSignalRoomL.setText("Signal Left Room");
  btnSignalRoomL.setTextBold();
  btnSignalRoomL.addEventHandler(this, "btnSignalRoomL_click1");
  btnSignalRoomR = new GButton(this, 150, 230, 80, 30);
  btnSignalRoomR.setText("Signal Right Room");
  btnSignalRoomR.setTextBold();
  btnSignalRoomR.addEventHandler(this, "btnSignalRoomR_click1");
  btnSignalCorridorL = new GButton(this, 50, 190, 80, 30);
  btnSignalCorridorL.setText("Signal  Left Corridor");
  btnSignalCorridorL.setTextBold();
  btnSignalCorridorL.addEventHandler(this, "btnSignalCorridorL_click1");
  btnScan = new GButton(this, 50, 270, 180, 30);
  btnScan.setText("Scan Room");
  btnScan.setTextBold();
  btnScan.addEventHandler(this, "btnScan_click1");
  btnSignalCorridorR = new GButton(this, 150, 190, 80, 30);
  btnSignalCorridorR.setText("Signal Right Corridor");
  btnSignalCorridorR.setTextBold();
  btnSignalCorridorR.addEventHandler(this, "btnSignalCorridorR_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextArea txtMsgFromZumo; 
GButton btnLeft; 
GButton btnRight; 
GButton btnForward; 
GButton btnBack; 
GButton btnStop; 
GButton btnSignalRoomL; 
GButton btnSignalRoomR; 
GButton btnSignalCorridorL; 
GButton btnScan; 
GButton btnSignalCorridorR; 