/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void txtMsgFromZumo_change1(GTextArea source, GEvent event) { //_CODE_:txtMsgFromZumo:653858:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtMsgFromZumo:653858:

public void btnMsgToZumo_click1(GButton source, GEvent event) { //_CODE_:btnMsgToZumo:500642:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnMsgToZumo:500642:

public void txtMsgToZumo_change1(GTextField source, GEvent event) { //_CODE_:txtMsgToZumo:568846:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtMsgToZumo:568846:

public void btnLeft_click1(GButton source, GEvent event) { //_CODE_:btnLeft:308221:

  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('A');
  println("A"); 
} //_CODE_:btnLeft:308221:

public void btnRight_click1(GButton source, GEvent event) { //_CODE_:btnRight:604378:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('D');
  println("D"); 
} //_CODE_:btnRight:604378:

public void btnForward_click1(GButton source, GEvent event) { //_CODE_:btnForward:348760:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('W');
  println("W");   
} //_CODE_:btnForward:348760:

public void btnBack_click1(GButton source, GEvent event) { //_CODE_:btnBack:984108:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('S');
  println("S"); 
} //_CODE_:btnBack:984108:

public void btnStop_click1(GButton source, GEvent event) { //_CODE_:btnStop:697225:
  println("btnStop - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('Q');
  println("Q");
} //_CODE_:btnStop:697225:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  txtMsgFromZumo = new GTextArea(this, 290, 30, 198, 199, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  txtMsgFromZumo.setText("Messages from Zumo");
  txtMsgFromZumo.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  txtMsgFromZumo.setOpaque(true);
  txtMsgFromZumo.addEventHandler(this, "txtMsgFromZumo_change1");
  btnMsgToZumo = new GButton(this, 190, 190, 91, 40);
  btnMsgToZumo.setTextAlign(GAlign.LEFT, GAlign.TOP);
  btnMsgToZumo.setText("Send message to Zumo");
  btnMsgToZumo.setTextBold();
  btnMsgToZumo.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  btnMsgToZumo.addEventHandler(this, "btnMsgToZumo_click1");
  txtMsgToZumo = new GTextField(this, 30, 190, 160, 30, G4P.SCROLLBARS_NONE);
  txtMsgToZumo.setText("Messages To Zumo");
  txtMsgToZumo.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  txtMsgToZumo.setOpaque(true);
  txtMsgToZumo.addEventHandler(this, "txtMsgToZumo_change1");
  btnLeft = new GButton(this, 10, 100, 80, 30);
  btnLeft.setText("Left");
  btnLeft.setTextBold();
  btnLeft.addEventHandler(this, "btnLeft_click1");
  btnRight = new GButton(this, 190, 100, 80, 31);
  btnRight.setText("Right");
  btnRight.setTextBold();
  btnRight.addEventHandler(this, "btnRight_click1");
  btnForward = new GButton(this, 100, 60, 80, 30);
  btnForward.setText("Forward");
  btnForward.setTextBold();
  btnForward.addEventHandler(this, "btnForward_click1");
  btnBack = new GButton(this, 100, 140, 80, 30);
  btnBack.setText("Back");
  btnBack.setTextBold();
  btnBack.addEventHandler(this, "btnBack_click1");
  btnStop = new GButton(this, 100, 100, 80, 29);
  btnStop.setText("Stop");
  btnStop.setTextBold();
  btnStop.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStop.addEventHandler(this, "btnStop_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextArea txtMsgFromZumo; 
GButton btnMsgToZumo; 
GTextField txtMsgToZumo; 
GButton btnLeft; 
GButton btnRight; 
GButton btnForward; 
GButton btnBack; 
GButton btnStop; 